---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - secure: "n7xy8EFMcorps7LseD00YpASqoGhOazSnhe0D5QnPqGreSvFznxlfI3\
      LYy6TkZ65zlj2ZlZ0AFwlFjSGgzipL/HR3rktqQ1yEWjlbicHy4Ne50rDrfi9RPg\
      zn0dCScKvXoFONDEsTPDaEX7mkd/eS2k2x4YSTpCcjt9k1lz/SwAAC/W5rOp9j50\
      EIRZqI/jXEpOSDeTSVjNlcKuoOsH04FZRZweXMs39Ut6wRHl0MoBTb6ekuX+qXe4\
      8XZLEDT6+HjZnUMnZhC8kxQlUob06XXNrUqCj9t9zmaiHjYCS2DYp884M4QfAFoK\
      WXwmH8OGMBpVJTQZSXm/zefBQ1RbLQdbR6f+rfNANtux0cDLggrrexhUiMoeVwcS\
      +fBPGzZ+jeANS3HJO4G61ZFV8KQu8T8LuMCwzvN25H4V5Aoj2TS5IySmncR3lvsr\
      FXsRx0HVhrOMaC1oq10lwsH+CXvByjTxoqUxV8YPjHpTZPvbkmf4vanhGMjYKKrq\
      2Yz9GKk94+A+oP5uICQC6waisCjpYd16qM5vSNbDbNMKl9+xUQ3gcHkGtzLPSkUD\
      l5dydag+6bDNLSZxNiiYYWgiTLFr9QFtgDtQ388rllJY1LTk//i2tyAsMBNt1Gh3\
      AZsXcCN1nQ/S5LnN3e2e5D9UYD8RWAdGGYyNMlQsvj38W2Ovn+FM="
    - secure: "XjPJ7J21vKhbeT8jTLt94GLUco5KwO/kwjstRymCIYgjKFEHoO4Av7u\
      jaZNdFgXOM/gjmqJk6UHN36v8Qex3BTnCKp8j37Qyl3GTMRnXavhIJhtNl+iE9WG\
      rKuH7qK464J/ZrGqmSSHBYJkqjfIAyytKgW8uQTqtQrSrBRCE+agYoidbZGCq0Pa\
      cGYhKWOawOMwXC4pbRZC0J0Y15oT7Q97VmDFEI6/AThNNXxOgs3vrxwvSLR51Nof\
      hFt9EhPfHJWIghV3raZaKfnOMNGgU6G+OlUr2t/djIRoDbsfOtxAg0Eq5JqhPN3p\
      2cQUA7ZFwDwKGXTyys/Ox+qEQXlAzYPhuLn3hlrCrpdGSB1SJgg+e3gSDRxL6Fgr\
      X9OfqDueI/6c2O8ZOgjWGyw1aHkYmRCjVycZVea5s28Ppj3q3SfmvK+aKbQWUcY0\
      2plOJM/dD2rRx+fI5g+pHtoA9q5N9uqWDs5pxem7WNcejNIs6S9RYA7k8/QRcKcq\
      iTUI45YYfNSMHJPJvq+T1NVG45/OWxL4gSIkKOc9ZDy1xd1Rr1I2n0TmiLY8Dnno\
      HgPl7KDTjzSZi211WalcHB9u1eHgcEfE+162e6UoXGSXN0JmpjigvlFcSVrsWjLU\
      Q56rYT0cCyvzc43vDfrffBUdiKHU34H5iVlCOkK6koUbeFNRf2PM="
    - secure: "FoIOZlGXmqq0Aw1xbXjYxulw1Go+fGWuaknrDi8o/TCeSnwZWnA15gN\
      MSvkihjAbYviQ/p+drpR5dT/i/u8P0wg6YFDAiLQvW5xwbuzkiW03+wgTKgm3Civ\
      oITkrVQeKufEyv7OGeEuW0rOFexzCA37mm5vZ89bGecSlieydYKyG2G3cmjmt9f6\
      TnypwSbxGJ7hFU0FP4RZ11wScbvrNwhiduW524g1w+B0/yQ54x3wQWYvmbcMel+R\
      C+/T6/yFRP19ZhXep4xA4YJbpmTsUqr1/PoJ0bUx1FdG3lGc2oFBnzrN9LcYqCPK\
      XOI05VOK2nLHwfAWCO0OS9SAfJm5izWzE+xHt4zXvIr/5THXRrI8IQA8u6pfzjvf\
      kQ5v3NaU5hu+QrINkthwgqCWhpuiiArM9UjDnVO/S5NhMFj33mYYLTOsAs3bQqIm\
      6AhPfI02SNgP7GGecx04oVF/lIZmkYebLZ/yXygXa00C1WRFhF51qZM1fMx0UINR\
      BOxytf33gQNZbe3WPC0kkRx+2TKhsVxHPpBq03KBrCCbG2g3pyoh4r3AT/+D+38J\
      0F4rwVGFflHKx47lqYO4+gYkR/v+4dKOWmY9Zb9wyxv32r+pSj9nnzaOb3dqkndp\
      LUIFcjTsm6t3ardVkfRGK95Cl6nQhP+HjjqNIXCITBpgjh/uf5YA="

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - molecule test
