---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: debian9
    image: debian:stretch-slim
  - name: debian10
    image: debian:buster-slim
  - name: fedora29
    image: fedora:29
  - name: fedora30
    image: fedora:30
  - name: amazon2018.03
    image: amazonlinux:2018.03
scenario:
  name: default
